import { container } from "tsyringe";
import UserRepository from "../repositories/userRepository.js";
import MongoDb from "../config/mongoConfig.js";
import UserServices from "../services/userServices.js";
import UserController from "../controllers/userController.js";
import CategoryService from "../services/categoryServices.js";
import CategoryRepository from "../repositories/categoryRepository.js";
import CategoryController from "../controllers/categoryController.js";
import ProductController from "../controllers/productController.js";
import ProductServices from "../services/productServices.js";
import ProductRepository from "../repositories/productRepository.js";
import CartRepository from "../repositories/cartRepository.js";
import CartService from "../services/cartServices.js";
import CartController from "../controllers/cartController.js";
import OrderRepository from "../repositories/orderRepository.js";
import OrderService from "../services/orderServices.js";
import OrderController from "../controllers/orderController.js";
import Utills from "../utils/utils.js";
import SellerRepository from "../repositories/sellerRepository.js";
import SellerServices from "../services/sellerServices.js";
import SellerController from "../controllers/sellerController.js";
import AuthServices from "../services/authServices.js";
import DataValidation from "../middlewares/validateData.js";
import ResponseHandler from "../utils/apiResponse.js";
import ErrorMiddleware from "../middlewares/errorMiddleware.js";
import EmailService from "../services/emailService1.js";
import PdfService from "../services/cloudService.js";
// import FactoryService from "../services/factoryService.js";

container.register(CategoryController, { useClass: CategoryController });
container.register(CategoryService, { useClass: CategoryService });
container.register(CategoryRepository, { useClass: CategoryRepository });
container.register(ProductController, { useClass: ProductController });
container.register(ProductServices, { useClass: ProductServices });
container.register(ProductRepository, { useClass: ProductRepository });
container.register(UserRepository, { useClass: UserRepository });
container.register(UserServices, { useClass: UserServices });
container.register(UserController, { useClass: UserController });
container.register(CartRepository, { useClass: CartRepository });
container.register(CartService, { useClass: CartService });
container.register(CartController, { useClass: CartController });
container.register(OrderRepository, { useClass: OrderRepository });
container.register(OrderService, { useClass: OrderService });
container.register(OrderController, { useClass: OrderController });
container.register(MongoDb, { useClass: MongoDb });
container.register(Utills, { useClass: Utills });
container.register(SellerRepository, { useClass: SellerRepository });
container.register(SellerServices, { useClass: SellerServices });
container.register(SellerController, { useClass: SellerController });
container.register(AuthServices, { useClass: AuthServices });
container.register(DataValidation, { useClass: DataValidation });
container.register(ResponseHandler, { useClass: ResponseHandler });
container.register(ErrorMiddleware, { useClass: ErrorMiddleware });
container.register(EmailService, { useClass: EmailService });
container.register(PdfService, { useClass: PdfService });
// container.register(FactoryService, {
//   useClass: FactoryService,
// });
// const isRegistered = container.isRegistered(UserController);
// console.log(isRegistered);
