import { container } from "tsyringe";
import UserRepository from "../repositories/userRepository";
import UserServices from "../services/userServices";
import UserController from "../controllers/userController";
import CategoryService from "../services/categoryServices";
import CategoryRepository from "../repositories/categoryRepository";
import CategoryController from "../controllers/categoryController";
import ProductController from "../controllers/productController";
import ProductServices from "../services/productServices";
import ProductRepository from "../repositories/productRepository";
import CartRepository from "../repositories/cartRepository";
import CartService from "../services/cartServices";
import CartController from "../controllers/cartController";
import OrderRepository from "../repositories/orderRepository";
import OrderService from "../services/orderServices";
import OrderController from "../controllers/orderController";
import SellerRepository from "../repositories/sellerRepository";
import SellerServices from "../services/sellerServices";
import SellerController from "../controllers/sellerController";
import AuthServices from "../services/authServices";
import DataValidation from "../middlewares/validateData";
import ResponseHandler from "../utils/apiResponse";
import ErrorMiddleware from "../middlewares/errorMiddleware";
import EmailService from "../services/emailService";
import PdfService from "../services/cloudService";
import FileRepository from "../repositories/fileRepository";
import AuditService from "../services/auditService";
// import FactoryService from "../services/factoryService";

container.register(CategoryController, { useClass: CategoryController });
container.register(CategoryService, { useClass: CategoryService });
container.register(CategoryRepository, { useClass: CategoryRepository });
container.register(ProductController, { useClass: ProductController });
container.register(ProductServices, { useClass: ProductServices });
container.register(ProductRepository, { useClass: ProductRepository });
container.register(UserRepository, { useClass: UserRepository });
container.register(UserServices, { useClass: UserServices });
container.register(UserController, { useClass: UserController });
container.register(CartRepository, { useClass: CartRepository });
container.register(CartService, { useClass: CartService });
container.register(CartController, { useClass: CartController });
container.register(OrderRepository, { useClass: OrderRepository });
container.register(OrderService, { useClass: OrderService });
container.register(OrderController, { useClass: OrderController });
container.register(SellerRepository, { useClass: SellerRepository });
container.register(SellerServices, { useClass: SellerServices });
container.register(SellerController, { useClass: SellerController });
container.register(AuthServices, { useClass: AuthServices });
container.register(DataValidation, { useClass: DataValidation });
container.register(ResponseHandler, { useClass: ResponseHandler });
container.register(ErrorMiddleware, { useClass: ErrorMiddleware });
container.register(EmailService, { useClass: EmailService });
container.register(PdfService, { useClass: PdfService });
container.register(FileRepository, { useClass: FileRepository });
container.register(AuditService, { useClass: AuditService });
// container.register(FactoryService, {
//   useClass: FactoryService,
// });
// const isRegistered = container.isRegistered(UserController);
// console.log(isRegistered);
